package by.epamtc.facultative.controller.command;

public enum CommandName {

	GO_TO_WELCOME_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_AUTHORIZATION_PAGE, REGISTRATION_COMMAND, 
	AUTHORIZATION_COMMAND, GO_TO_USER_PAGE, GO_TO_LECTURER_PAGE, GO_TO_DEAN_PAGE, 
	GO_TO_RECTOR_PAGE, GO_TO_ERROR_PAGE, CHANGE_LANGUAGE, GO_TO_REGISTRATION_SUCCESS_PAGE,
	UPLOAD_USER_PHOTO, EDIT_USER_INFO

}
