package by.epamtc.facultative.controller.command;

public enum CommandName {

	GO_TO_WELCOME_PAGE, 
	GO_TO_REGISTRATION_PAGE, 
	GO_TO_AUTHORIZATION_PAGE, 
	REGISTRATION_COMMAND, 
	AUTHORIZATION_COMMAND, 
	GO_TO_LECTURER_PAGE, 
	GO_TO_DEAN_PAGE, 
	GO_TO_RECTOR_PAGE, 
	GO_TO_ERROR_PAGE, 
	CHANGE_LANGUAGE, 
	UPLOAD_USER_PHOTO, 
	EDIT_USER_INFO, 
	CREATE_COURSE_COMMAND, 
	LOGOUT, 
	
	
	GO_TO_USER_PAGE, 
	GO_TO_REGISTRATION_SUCCESS_PAGE,
	GO_TO_EDIT_USER_INFO_COMMAND, 
	GO_TO_USER_COURSES_PAGE,
	GO_TO_USER_RATING_PAGE, 
	GO_TO_CREATE_RUN_COURSE_PAGE, 
	GO_TO_RUN_COURSE_PAGE,
	GO_TO_COURSE_PAGE_COMMAND, 
	GO_TO_DEPARTMENTS_PAGE, 
	GO_TO_UNIVERCITY_COURSES_PAGE, 
	GO_TO_CONTACTS_PAGE,
	GO_TO_NEWS_PAGE, 
	GO_TO_ABOUT_UNIVERSITY_PAGE, 
	GO_TO_AVAILABLE_RUN_COURSES_PAGE, 
	GO_TO_CURRENT_DEPARTMENT_PAGE_COMMAND,
	GO_TO_STAFF_PAGE,
	
	GO_TO_SUCCESS_PAGE_COMMAND,
	
	APPLY_FOR_COURSE, 
	REMOVE_APPLICATION_FOR_COURSE, 

	APPROVE_STUDENT_ON_COURSE, 
	DISAPPROVE_STUDENT_ON_COURSE, 
	DROP_OUT_STUDENT_FROM_COURSE, 
	
	APPROVE_EMPLOYEE,
	DISAPPROVE_EMPLOYEE,
	GO_TO_ANOTHER_USER_PAGE,
	
	}
